spring.application.name=forohub

spring.datasource.url=jdbc:mysql://localhost/forohub_api
spring.datasource.username=root
spring.datasource.password=12345678

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.web.error.include-stacktrace=never

api.security.token.secret=${JWT_SECRET:12345678}